// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb6-BBpwAyLQJB-zGRqSp8tfiLUoIn8mo',
    appId: '1:1017834612507:web:d22958ab5774247cf495be',
    messagingSenderId: '1017834612507',
    projectId: 'freebie-coffee-app',
    authDomain: 'freebie-coffee-app.firebaseapp.com',
    storageBucket: 'freebie-coffee-app.appspot.com',
    measurementId: 'G-0EGS81W3RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyXH7OK0NiQp6PVn5SRJsxwZS5b_Ipr4M',
    appId: '1:1017834612507:android:e0fe41b14739e6d9f495be',
    messagingSenderId: '1017834612507',
    projectId: 'freebie-coffee-app',
    storageBucket: 'freebie-coffee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgoFAJ50rrubRziuJowWHSnlx4yzaiEAY',
    appId: '1:1017834612507:ios:aa58c547fba8e01ff495be',
    messagingSenderId: '1017834612507',
    projectId: 'freebie-coffee-app',
    storageBucket: 'freebie-coffee-app.appspot.com',
    iosClientId: '1017834612507-ss914h433kkrpbapsgim8vhkkh2qfn99.apps.googleusercontent.com',
    iosBundleId: 'com.example.freebieCoffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgoFAJ50rrubRziuJowWHSnlx4yzaiEAY',
    appId: '1:1017834612507:ios:b42706e2e01b0aaaf495be',
    messagingSenderId: '1017834612507',
    projectId: 'freebie-coffee-app',
    storageBucket: 'freebie-coffee-app.appspot.com',
    iosClientId: '1017834612507-mpkrp8jnbura2v3rrm9oupm1tomciu5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.freebieCoffeeApp.RunnerTests',
  );
}
